######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 26 17:06:17 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += AddStockDialog.h MainWindow.h Stock.h
SOURCES += AddStockDialog.cpp main.cpp MainWindow.cpp Stock.cpp
RESOURCES += resources.qrc
